name: Generate Podcast

on:
  push:
    branches:
      - main
    paths:
      - '_posts/**/*.md'
      - '_vibecoding/**/*.md'

  workflow_dispatch:  # Toto umožní manuální spuštění

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub pyyaml

    - name: Run script
      env:
        ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python .github/scripts/podcast-automation-script.py

    - name: Send OneSignal Notification
      env:
        ONESIGNAL_REST_API_KEY: ${{ secrets.ONESIGNAL_REST_API_KEY }}
        ONESIGNAL_APP_ID: ${{ secrets.ONESIGNAL_APP_ID }}
      run: python .github/scripts/send_onesignal_notification.py
