name: Generate Podcast

on:
  push:
    branches:
      - main
    paths:
      - '_posts/**'
  workflow_dispatch:  # Toto umožní manuální spuštění   

jobs:
  generate_podcast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub pyyaml feedgenerator elevenlabs
    
    - name: List installed packages
      run: pip list

    - name: Check ElevenLabs version
      run: pip show elevenlabs
    
    - name: Run podcast generation script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      run: python .github/scripts/podcast-automation-script.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add podcast_feed.xml audio/
        git commit -m "Update podcast feed and audio" || exit 0
        git push
